blank_issues_enabled: false
contact_links:
  - name: UPENN-PNGC
    url: https://github.com/UPENN-PNGC
    about: PNGC GitHub Organization
  - name: About PNGC
    url: https://www.penn-ngc.org/
    about: PNGC Website
  - name: PNGC Training Discussions
    url: https://github.com/UPENN-PNGC/pngc-training/discussions
    about: Ask questions or get help about course topics or materials.
